# Generated by Django 6.0.3 on 2026-04-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='labels.label', verbose_name='labels'),
        ),
    ]
